# -*- coding: utf-8 -*-
{
    'name': 'Matelas',
    'version': '19.0.1.0.10',
    'summary': 'Site e-commerce de vente de matelas',
    'category': 'Website',
    'depends': [
        'website',
        'website_sale',
        'sale',
        'account',
        'im_livechat',
        'website_livechat',
        'mass_mailing',
        'website_mass_mailing',
        'crm',
        'payment_demo',
        'auth_signup',
    ],
    'author': 'Equipe matelas',
    'license': 'LGPL-3',

    'data': [
        'security/ir.model.access.csv',
        'data/product_tags_data.xml',
        'data/languages_data.xml',
        'data/livechat_data.xml',
        'data/website_config.xml',
        'data/payment_data.xml',
        'data/newsletter_data.xml',
        'data/footer.xml',
        'data/header_templates.xml',
        'data/mail_template.xml',
        'data/branding_data.xml',
        'views/website_layout_head.xml',
        'views/product_template_views.xml',
        'views/newsletter_wizard_views.xml',
        'views/avis_views.xml',
        'views/contact_message_views.xml',
        'views/templates/home.xml',
        'views/templates/avis.xml',
        'views/templates/contact.xml',
        'views/templates/mentions_legales.xml',
        'views/templates/cookies.xml',
        'views/templates/fiche_technique.xml',
        'views/templates/email_confirm.xml',
        'data/seo_data.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            'matelas/static/src/css/lib/bootstrap-icons/bootstrap-icons.css',
            'matelas/static/src/css/Home.css',
            'matelas/static/src/css/Avis.css',
            'matelas/static/src/css/Contact.css',
            'matelas/static/src/css/Mentions.css',
            'matelas/static/src/css/Shop.css',
            'matelas/static/src/css/FicheTechnique.css',
            'matelas/static/src/css/PortalAccount.css',
            'matelas/static/src/js/main.js',
            'matelas/static/src/js/fiche_technique.js',
        ],
    },
    'application': True,
    'post_init_hook': '_assign_nouveaute_tag',

}
