const products = [
  {
    id: 1,
    name: "Velvet Lip Rouge",
    category: "Lips",
    price: 28,
    icon: "fa-heart",
    shade: "#c17e8a",
    img: "products/lip-rouge.jpg",
    description: "A richly pigmented lip colour with a velvety matte finish. Infused with vitamin E and shea butter, it glides on effortlessly delivering all-day hydration alongside bold, buildable colour that never feathers or fades.",
    type: "Lip Colour",
    finish: "Matte Velvet",
    bestFor: "Long-lasting wear",
    keyIngredients: "Shea Butter, Vitamin E, Jojoba Oil",
    rating: 4.8,
    reviews: 214,
    shades: [
      { color: "#c17e8a", name: "Rose Petal" },
      { color: "#a8445a", name: "Berry Kiss" },
      { color: "#d4a0a8", name: "Dusty Pink" },
      { color: "#8b3a4a", name: "Midnight Rose" },
      { color: "#e8c0c8", name: "Blush Nude" }
    ]
  },
  {
    id: 2,
    name: "Radiance Serum",
    category: "Skincare",
    price: 65,
    icon: "fa-droplet",
    shade: "#d4b896",
    img: "products/serum.jpg",
    description: "A concentrated brightening serum that targets dullness and uneven skin tone. Formulated with 15% stabilised Vitamin C and multi-weight hyaluronic acid for a visible, glass-skin glow in just 7 days.",
    type: "Brightening Serum",
    finish: "Skin Care",
    bestFor: "Dull & uneven skin",
    keyIngredients: "Vitamin C 15%, Hyaluronic Acid, Niacinamide",
    rating: 4.9,
    reviews: 389,
    shades: []
  },
  {
    id: 3,
    name: "Silk Veil Foundation",
    category: "Face",
    price: 48,
    icon: "fa-face-smile",
    shade: "#e8d5c4",
    img: "products/foundation.jpg",
    description: "A weightless, buildable foundation with a natural skin-like finish. Enriched with squalane and SPF 20, it blurs imperfections and evens tone while letting your skin breathe all day long.",
    type: "Liquid Foundation",
    finish: "Natural Satin",
    bestFor: "Buildable coverage",
    keyIngredients: "Squalane, SPF 20, Hyaluronic Acid",
    rating: 4.7,
    reviews: 176,
    shades: [
      { color: "#f5e6d0", name: "Porcelain" },
      { color: "#ecd5b8", name: "Ivory" },
      { color: "#d4b896", name: "Sand" },
      { color: "#c4a07a", name: "Warm Beige" },
      { color: "#a07850", name: "Caramel" },
      { color: "#6b4c30", name: "Espresso" }
    ]
  },
  {
    id: 4,
    name: "Hydra Night Cream",
    category: "Skincare",
    price: 72,
    icon: "fa-moon",
    shade: "#9baab8",
    img: "products/night-cream.jpg",
    description: "An intensely nourishing overnight treatment that works while you sleep. A blend of retinol, ceramides, and rosehip oil restores moisture, smooths fine lines, and leaves skin visibly plumper by morning.",
    type: "Night Cream",
    finish: "Skin Care",
    bestFor: "Dry & mature skin",
    keyIngredients: "Retinol 0.3%, Ceramides, Rosehip Oil",
    rating: 4.9,
    reviews: 302,
    shades: []
  },
  {
    id: 5,
    name: "Smoky Eye Palette",
    category: "Eyes",
    price: 55,
    icon: "fa-eye",
    shade: "#8b7d8a",
    img: "products/palette.jpg",
    description: "Twelve highly pigmented eyeshadows ranging from champagne to deep charcoal. The perfectly curated mix of mattes and shimmers blend effortlessly for every look — from soft day wear to a dramatic smoky eye.",
    type: "Eyeshadow Palette",
    finish: "Mixed — Matte & Shimmer",
    bestFor: "Day to night looks",
    keyIngredients: "Mica, Kaolin Clay, Vitamin E",
    rating: 4.8,
    reviews: 421,
    shades: [
      { color: "#e8e0d0", name: "Champagne" },
      { color: "#c8b89a", name: "Sand Dune" },
      { color: "#a89070", name: "Taupe" },
      { color: "#786050", name: "Mink" },
      { color: "#504038", name: "Smoke" },
      { color: "#2a2018", name: "Onyx" }
    ]
  },
  {
    id: 6,
    name: "Fix & Mist Spray",
    category: "Face",
    price: 32,
    icon: "fa-spray-can",
    shade: "#b8cfc4",
    img: "products/mist.jpg",
    description: "A refreshing setting spray that locks in makeup for up to 16 hours. Enriched with aloe vera and green tea extract to hydrate, soothe, and keep your complexion fresh from morning to evening.",
    type: "Setting Spray",
    finish: "Dewy / Natural",
    bestFor: "Makeup longevity",
    keyIngredients: "Aloe Vera, Green Tea Extract, Rose Water",
    rating: 4.6,
    reviews: 158,
    shades: []
  },
  {
    id: 7,
    name: "Satin Blush",
    category: "Face",
    price: 38,
    icon: "fa-heart",
    shade: "#e8b4b8",
    img: "products/blush.jpg",
    description: "A silky powder blush that melts into skin for a natural, sun-kissed flush. Finely milled pigments build from sheer to vibrant, staying fresh and blendable from morning to night.",
    type: "Powder Blush",
    finish: "Satin",
    bestFor: "Natural flush & glow",
    keyIngredients: "Silica, Mica, Vitamin E",
    rating: 4.7,
    reviews: 193,
    shades: [
      { color: "#f0c8c8", name: "Baby Rose" },
      { color: "#e8b4b8", name: "Peach Bliss" },
      { color: "#d4828a", name: "Coral Kiss" },
      { color: "#c96070", name: "Berry Flush" },
      { color: "#e87890", name: "Hot Pink" }
    ]
  },
  {
    id: 8,
    name: "Lash Luxe Mascara",
    category: "Eyes",
    price: 24,
    icon: "fa-eye",
    shade: "#3d3533",
    img: "products/mascara.jpg",
    description: "A volumising and lengthening mascara with a precision hourglass brush that coats every lash from root to tip. Buildable, clump-free formula delivers a dramatically full effect that lasts all day.",
    type: "Mascara",
    finish: "High Gloss",
    bestFor: "Volume & length",
    keyIngredients: "Beeswax, Panthenol, Castor Oil",
    rating: 4.5,
    reviews: 267,
    shades: [
      { color: "#1a1a1a", name: "Noir" },
      { color: "#3d2b1f", name: "Espresso Brown" },
      { color: "#2a2a4a", name: "Midnight Navy" }
    ]
  },
  {
    id: 9,
    name: "Glow Highlighter",
    category: "Face",
    price: 42,
    icon: "fa-star",
    shade: "#d4c4a0",
    img: "products/highlighter.jpg",
    description: "A finely milled powder highlighter with a prismatic, multi-dimensional finish. Reflects light from every angle for a luminous, lit-from-within glow on cheekbones, brow bones, and the cupid's bow.",
    type: "Powder Highlighter",
    finish: "Prismatic Glow",
    bestFor: "Luminous & radiant skin",
    keyIngredients: "Pearl Powder, Mica, Vitamin C",
    rating: 4.8,
    reviews: 144,
    shades: [
      { color: "#f0e0b8", name: "Champagne Gold" },
      { color: "#d4c4a0", name: "Warm Pearl" },
      { color: "#e8d4c0", name: "Rose Gold" },
      { color: "#c0b08a", name: "Bronze Glow" }
    ]
  }
];
