# -*- coding: utf-8 -*-
{
    'name': "Mandat administratif (Chorus Pro)",
    'version': '19.0.2.0.0',
    'category': 'Accounting/Payment Providers',
    'summary': "Paiement par mandat administratif pour les entités publiques françaises — dépôt des factures sur Chorus Pro",
    'author': "EXOCOMS Group",
    'website': "https://www.exocoms.fr",
    'license': 'LGPL-3',
    'depends': [
        'payment',
        'account',
        'sale_management',
        'website_sale',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/payment_form_templates.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
        'data/sequence_data.xml',
        'views/payment_provider_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/mandat_confirmation_page.xml',
        'views/snippets/s_mandat_administratif.xml',
        'views/snippets/snippets.xml',
        'report/report_action.xml',
        'report/bca_template.xml',
        'wizard/mandat_wizard_views.xml',
        'wizard/service_fait_wizard_views.xml',
        'wizard/pec_wizard_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'mandat_administratif/static/src/snippets/s_mandat_administratif/000.scss',
            'mandat_administratif/static/src/payment_badge.scss',
            'mandat_administratif/static/src/interactions/payment_badge.js',
        ],
        'payment.assets_payment_form_content': [
            'mandat_administratif/static/src/js/mandat_checkout.js',
        ],
    },
    'images': ['static/description/icon.png'],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'application': False,
}
