from . import product_spec_category
from . import product_spec_attribute
from . import product_template_spec_line
from . import product_template
from . import res_config_settings
from . import product_spec_carrier
from . import delivery_carrier
from . import sale_order
from . import product_spec_autofetch
from . import product_spec_marketplace
from . import product_spec_api_key
