{
    'name': 'Exocoms Infogérance',
    'version': '1.0',
    'summary': 'Gestion d\'infogérance, abonnements, contrats et helpdesk pour Exocoms Group',
    'author': 'Exocoms Group',
    'license': 'LGPL-3',
    'category': 'Services',
    'depends': [
        'website',
        'website_sale',
        'sale_subscription',
        'helpdesk',
        'helpdesk_sale',
        'rating',
        'mail',
        'portal',
        'product',
        'exocoms_theme',
    ],
    'data': [
        'security/ir.model.access.csv',
        # 'data/product_data.xml',  # Désactivé temporairement — créé manuellement via UI
        'data/helpdesk_data.xml',
        'data/infogerance_data.xml',
        'views/infogerance_contract_views.xml',
        'views/infogerance_equipment_views.xml',
        'views/infogerance_service_views.xml',
        'views/helpdesk_extend_views.xml',
        'views/infogerance_portal_templates.xml',
        'views/infogerance_web_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'exocoms_infogerance/static/src/css/infogerance.css',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'post_migrate': 'post_migrate_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
}
