# -*- coding: utf-8 -*-
from . import rgpd_data_category
from . import rgpd_subject_category
from . import rgpd_recipient
from . import rgpd_engine
from . import rgpd_treatment
from . import rgpd_data_map
from . import rgpd_consent_purpose
from . import rgpd_consent
from . import rgpd_request
from . import rgpd_retention_rule
from . import rgpd_breach
from . import rgpd_audit_rule
from . import rgpd_audit_log
from . import base_audit
from . import rgpd_blacklist_sync
from . import res_company
from . import res_config_settings
from . import res_partner
