{
    'name': 'Luxury Services',
    'version': '19.0.1.0.0',
    'summary': 'Gestion des yachts, jets et services VIP',
    'author': 'Exocoms',
    'category': 'eCommerce',
    'depends': ['product', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_views.xml',
        'views/reservation_views.xml',
        'views/templates.xml',
        'views/luxury_destination_views.xml',
        'views/maintenance_views.xml',
        'views/maintenance_back_views.xml',
        'views/destination_views.xml',
        'views/a_propos_views.xml',
        'views/service_convierge_views.xml',
        'views/concierge_back_views.xml',
        'views/home_page_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'luxury_services/static/src/scss/custom.scss',
            'luxury_services/static/src/js/luxury_custom.scss',
        ],
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}