{
    'name': 'Exocoms Theme',
    'version': '1.0',
    'summary': 'Custom website theme for Exocoms Group',
    'author': 'Exocoms Group',
    'license': 'LGPL-3',
    'category': 'Website',
    'depends': [
        'website',
        'website_sale',
        'im_livechat',
    ],
    'data': [
        'data/website_data.xml',
        'views/pages/home.xml',
        'views/pages/services.xml',
        'views/pages/mentions_legales.xml',
        'views/pages/boutique.xml',
        'views/partials/hero.xml',
        'views/partials/dashbord.xml',
        'views/partials/dashbord_boutique.xml',
        'views/partials/services_hero.xml',
        'views/partials/services_content.xml',
        'views/partials/mentions_legales_content.xml',
        'views/partials/portal.xml',
        'views/templates/header.xml',
        'views/templates/footer.xml',
        'views/templates/features.xml',
        'views/templates/layout.xml',
        'views/templates/services_features.xml',
        'data/seo_data.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'post_migrate': 'post_migrate_hook',
    'installable': True,
    'application': True,
}