# -*- coding: utf-8 -*-

GAMME_STATUS_DISPONIBLE = 'disponible'
GAMME_STATUS_A_CONFIRMER = 'a_confirmer'

GAMMES_DATA = [
    {
        'slug': 'capsule',
        'status': GAMME_STATUS_DISPONIBLE,
        'icon': 'fa-home',
        'name': 'Capsule',
        'indicative': True,
        'tagline_fr': '3 tailles disponibles · 18 à 40 m²',
        'tagline_en': '3 sizes available · 18 to 40 sqm',
        'performances': [
            {'icon': 'fa-square-o', 'title_fr': 'Vitrage isolant', 'title_en': 'Insulating glazing',
             'desc_fr': 'Double vitrage, isolation optimale (NF EN 1279)', 'desc_en': 'Double glazing, optimal insulation (NF EN 1279)'},
            {'icon': 'fa-lock', 'title_fr': 'Serrure sécurisée', 'title_en': 'Secure lock',
             'desc_fr': 'Accès à code, sécurité renforcée', 'desc_en': 'Code access, enhanced security'},
            {'icon': 'fa-lightbulb-o', 'title_fr': 'Éclairage LED encastré', 'title_en': 'Recessed LED lighting',
             'desc_fr': 'Lumière chaude + rubans LED étanches extérieurs', 'desc_en': 'Warm light + weatherproof outdoor LED strips'},
            {'icon': 'fa-bath', 'title_fr': 'Salle de bain équipée', 'title_en': 'Equipped bathroom',
             'desc_fr': 'Miroir, vasque, douche vitrée', 'desc_en': 'Mirror, sink, glass shower'},
            {'icon': 'fa-sun-o', 'title_fr': 'Puits de lumière', 'title_en': 'Skylight',
             'desc_fr': 'Vitrage isolant + store motorisé', 'desc_en': 'Insulating glazing + motorised blind'},
            {'icon': 'fa-paint-brush', 'title_fr': 'Design aluminium', 'title_en': 'Aluminium design',
             'desc_fr': 'Panneaux aluminium intérieur et extérieur', 'desc_en': 'Aluminium panels inside and out'},
            {'icon': 'fa-bolt', 'title_fr': 'Alimentation électrique', 'title_en': 'Electrical supply',
             'desc_fr': 'Câblage cuivre, installation NF C 15-100', 'desc_en': 'Copper wiring, NF C 15-100 installation'},
            {'icon': 'fa-arrows-v', 'title_fr': 'Escalier 3 marches', 'title_en': '3-step staircase',
             'desc_fr': 'Acier léger + bois composite inclus', 'desc_en': 'Lightweight steel + composite wood included'},
            {'icon': 'fa-building-o', 'title_fr': 'Structure solide', 'title_en': 'Solid structure',
             'desc_fr': 'Anneau de levage + support galvanisé', 'desc_en': 'Lifting ring + galvanised support'},
        ],
        'formats': [
            {'name': 'Studio', 'surface_fr': '18-20 m²', 'surface_en': '18-20 sqm',
             'note_fr': 'Compact', 'note_en': 'Compact'},
            {'name': 'Duo', 'surface_fr': '26-30 m²', 'surface_en': '26-30 sqm',
             'note_fr': "Jusqu'à 4 pers.", 'note_en': 'Up to 4 people'},
            {'name': 'Panorama', 'surface_fr': '36-40 m²', 'surface_en': '36-40 sqm',
             'note_fr': '4 à 6 pers.', 'note_en': '4 to 6 people'},
        ],
        'specs_ext': [
            {'label_fr': 'Façade', 'label_en': 'Facade',
             'value_fr': 'Panneau aluminium', 'value_en': 'Aluminium panel'},
            {'label_fr': "Porte d'entrée", 'label_en': 'Entrance door',
             'value_fr': 'Inox + serrure à code', 'value_en': 'Stainless steel + code lock'},
            {'label_fr': 'Vitrage', 'label_en': 'Glazing',
             'value_fr': 'Vitrage isolant NF EN 1279', 'value_en': 'Insulating glazing NF EN 1279'},
            {'label_fr': 'Fenêtres', 'label_en': 'Windows',
             'value_fr': 'Performances NF EN 14351-1', 'value_en': 'Performance NF EN 14351-1'},
        ],
        'specs_int': [
            {'label_fr': 'Sol principal', 'label_en': 'Main floor',
             'value_fr': 'Revêtement SPC', 'value_en': 'SPC flooring'},
            {'label_fr': 'Électricité', 'label_en': 'Electrical',
             'value_fr': 'Installation NF C 15-100', 'value_en': 'NF C 15-100 wiring'},
            {'label_fr': 'Automatismes', 'label_en': 'Automation',
             'value_fr': 'Store motorisé (option)', 'value_en': 'Motorised blind (option)'},
        ],
        'equipements_fr': [
            'Cadre acier galvanisé', 'Fenêtres double vitrage',
            'Construction isolée et étanche', 'Sanitaire équipé (WC, douche, lavabo)',
            'Installation électrique NF C 15-100', 'Verrouillage sécurisé',
        ],
        'equipements_en': [
            'Galvanised steel frame', 'Double-glazed windows',
            'Insulated, weatherproof construction', 'Equipped bathroom (toilet, shower, sink)',
            'NF C 15-100 electrical wiring', 'Secure locking',
        ],
        'options_fr': ['Chauffage additionnel', 'Isolation renforcée', 'Triple vitrage', 'Aménagement sur mesure'],
        'options_en': ['Additional heating', 'Reinforced insulation', 'Triple glazing', 'Custom fit-out'],
        'usages': ['Logement', 'Bureau', 'Résidence secondaire', 'Location & Airbnb'],
    },
    {
        'slug': 'cabine',
        'status': GAMME_STATUS_DISPONIBLE,
        'icon': 'fa-th-large',
        'name': 'Cabine',
        'indicative': True,
        'tagline_fr': '3 tailles disponibles · 10 à 25 m²',
        'tagline_en': '3 sizes available · 10 to 25 sqm',
        'performances': [
            {'icon': 'fa-tree', 'title_fr': 'Structure bois & acier', 'title_en': 'Wood & steel structure',
             'desc_fr': 'Châssis robuste et bardage haute résistance', 'desc_en': 'Robust chassis and high-resistance cladding'},
            {'icon': 'fa-sun-o', 'title_fr': 'Lumière naturelle', 'title_en': 'Natural light',
             'desc_fr': 'Grande baie vitrée panoramique', 'desc_en': 'Large panoramic glass window'},
            {'icon': 'fa-shield', 'title_fr': 'Isolation thermique', 'title_en': 'Thermal insulation',
             'desc_fr': 'Isolation 4 saisons (mousse haute densité / laine de roche)', 'desc_en': '4-season insulation (high-density foam / rock wool)'},
            {'icon': 'fa-plug', 'title_fr': 'Plug & Play', 'title_en': 'Plug & Play',
             'desc_fr': 'Prête à raccorder (électricité + eau)', 'desc_en': 'Ready to connect (electricity + water)'},
            {'icon': 'fa-volume-off', 'title_fr': 'Isolation acoustique', 'title_en': 'Acoustic insulation',
             'desc_fr': 'Confort phonique optimisé pour le travail', 'desc_en': 'Optimised sound comfort for work'},
            {'icon': 'fa-compress', 'title_fr': 'Emprise optimisée', 'title_en': 'Optimised footprint',
             'desc_fr': "S'intègre facilement dans tous les jardins", 'desc_en': 'Easily integrates into any garden'},
            {'icon': 'fa-bolt', 'title_fr': 'Électricité intégrée', 'title_en': 'Integrated electricity',
             'desc_fr': 'Prises, interrupteurs et tableau pré-câblé NF C 15-100', 'desc_en': 'Outlets, switches and pre-wired NF C 15-100 panel'},
            {'icon': 'fa-paint-brush', 'title_fr': 'Finition moderne', 'title_en': 'Modern finish',
             'desc_fr': 'Habillage intérieur bois chaleureux ou design contemporain', 'desc_en': 'Warm interior wood panelling or contemporary design'},
        ],
        'formats': [
            {'name': 'Solo / Bureau', 'surface_fr': '10-12 m²', 'surface_en': '10-12 sqm',
             'note_fr': 'Idéal télétravail / Micro-office', 'note_en': 'Ideal for home office'},
            {'name': 'Comfort', 'surface_fr': '15-18 m²', 'surface_en': '15-18 sqm',
             'note_fr': "Chambre d'amis / Studio", 'note_en': 'Guest room / Studio'},
            {'name': 'Lodge', 'surface_fr': '20-25 m²', 'surface_en': '20-25 sqm',
             'note_fr': 'Hébergement équipé (2 à 4 pers.)', 'note_en': 'Equipped accommodation (2 to 4 people)'},
        ],
        'specs_ext': [
            {'label_fr': 'Bardage', 'label_en': 'Cladding',
             'value_fr': 'Bois composite / Acier traité', 'value_en': 'Composite wood / Treated steel'},
            {'label_fr': 'Baies & Ouvertures', 'label_en': 'Openings',
             'value_fr': 'Châssis aluminium rupture de pont thermique', 'value_en': 'Thermal break aluminium frames'},
            {'label_fr': 'Toiture', 'label_en': 'Roofing',
             'value_fr': 'Étanchéité EPDM / Bac acier isolé', 'value_en': 'EPDM waterproofing / Insulated steel deck'},
            {'label_fr': 'Vitrage', 'label_en': 'Glazing',
             'value_fr': 'Double vitrage feuilleté sécurit', 'value_en': 'Double-glazed laminated safety glass'},
        ],
        'specs_int': [
            {'label_fr': 'Revêtement sol', 'label_en': 'Flooring',
             'value_fr': 'Parquet stratifié ou vinyle haut passage', 'value_en': 'Laminate or heavy-duty vinyl flooring'},
            {'label_fr': 'Murs & Plafond', 'label_en': 'Walls & Ceiling',
             'value_fr': 'Panneaux bois PEFC / Placo peint', 'value_en': 'PEFC wood panels / Painted plasterboard'},
            {'label_fr': 'Électricité', 'label_en': 'Electrical',
             'value_fr': 'Installation conforme NF C 15-100', 'value_en': 'NF C 15-100 compliant installation'},
        ],
        'equipements_fr': [
            'Châssis autoportant en acier',
            'Isolation thermique et acoustique renforcée',
            'Éclairage LED intérieur encastré',
            'Tableau électrique pré-équipé',
            "Ventilation mécanique / Grilles d'aération",
            'Serrure de sécurité à clé ou digicode',
        ],
        'equipements_en': [
            'Self-supporting steel frame',
            'Reinforced thermal and acoustic insulation',
            'Recessed interior LED lighting',
            'Pre-equipped electrical panel',
            'Mechanical ventilation / Air vents',
            'Key or keypad security lock',
        ],
        'options_fr': [
            'Climatisation réversible (Pompe à chaleur)',
            'Panneaux solaires en toiture',
            'Kitchinette équipée',
            "Salle d'eau compacte (WC + douche)",
            'Terrasse extérieure en bois',
        ],
        'options_en': [
            'Reversible air conditioning (Heat pump)',
            'Rooftop solar panels',
            'Equipped kitchenette',
            'Compact bathroom (toilet + shower)',
            'Outdoor wooden deck',
        ],
        'usages': [
            'Bureau de jardin / Télétravail',
            "Chambre d'amis / Studio d'adolescent",
            "Atelier d'artiste / Salle de sport",
            'Gîte / Hébergement insolite',
        ],
    },
    {
        'slug': 'dome',
        'status': GAMME_STATUS_DISPONIBLE,
        'icon': 'fa-circle-o',
        'name': 'Dôme',
        'indicative': True,
        'tagline_fr': '3 tailles disponibles · 19 à 50 m²',
        'tagline_en': '3 sizes available · 19 to 50 sqm',
        'performances': [
            {'icon': 'fa-refresh', 'title_fr': 'Structure triangulée', 'title_en': 'Triangulated structure',
            'desc_fr': 'Excellente résistance aux vents forts et à la neige', 'desc_en': 'Strong resistance to high winds and snow load'},
            {'icon': 'fa-square-o', 'title_fr': 'Vitrage isolant', 'title_en': 'Insulating glazing',
            'desc_fr': 'Double vitrage sécurit, isolation optimale (NF EN 1279)', 'desc_en': 'Tempered double glazing, optimal insulation (NF EN 1279)'},
            {'icon': 'fa-thermometer-half', 'title_fr': 'Isolation renforcée', 'title_en': 'Enhanced insulation',
            'desc_fr': 'Panneaux isolants, faibles déperditions grâce à la forme sans angles', 'desc_en': 'Insulated panels, low heat loss thanks to the angle-free shape'},
            {'icon': 'fa-bath', 'title_fr': 'Salle de bain équipée', 'title_en': 'Equipped bathroom',
            'desc_fr': 'Miroir, vasque, douche vitrée', 'desc_en': 'Mirror, sink, glass shower'},
            {'icon': 'fa-lightbulb-o', 'title_fr': 'Éclairage LED encastré', 'title_en': 'Recessed LED lighting',
            'desc_fr': 'Lumière chaude intérieure et extérieure', 'desc_en': 'Warm interior and exterior lighting'},
            {'icon': 'fa-building-o', 'title_fr': 'Structure aluminium', 'title_en': 'Aluminium structure',
            'desc_fr': 'Ossature légère et durable, laquée', 'desc_en': 'Lightweight, durable, lacquered frame'},
            {'icon': 'fa-bolt', 'title_fr': 'Alimentation électrique', 'title_en': 'Electrical supply',
            'desc_fr': 'Câblage cuivre, installation NF C 15-100', 'desc_en': 'Copper wiring, NF C 15-100 installation'},
            {'icon': 'fa-tint', 'title_fr': 'Ventilation anti-humidité', 'title_en': 'Anti-humidity ventilation',
            'desc_fr': 'Circulation d\'air optimisée par la forme sphérique', 'desc_en': 'Optimised air circulation thanks to the spherical shape'},
        ],
        'formats': [
            {'name': 'Compact', 'surface_fr': '19-20 m²', 'surface_en': '19-20 sqm',
            'note_fr': 'Jusqu\'à 2 pers.', 'note_en': 'Up to 2 people'},
            {'name': 'Confort', 'surface_fr': '28-30 m²', 'surface_en': '28-30 sqm',
            'note_fr': 'Jusqu\'à 4 pers.', 'note_en': 'Up to 4 people'},
            {'name': 'Panoramique', 'surface_fr': '38-50 m²', 'surface_en': '38-50 sqm',
            'note_fr': '4 à 6 pers.', 'note_en': '4 to 6 people'},
        ],
        'specs_ext': [
            {'label_fr': 'Structure', 'label_en': 'Structure',
            'value_fr': 'Aluminium laqué triangulé', 'value_en': 'Triangulated lacquered aluminium'},
            {'label_fr': 'Vitrage', 'label_en': 'Glazing',
            'value_fr': 'Double vitrage sécurit NF EN 1279', 'value_en': 'Tempered double glazing NF EN 1279'},
            {'label_fr': 'Porte d\'entrée', 'label_en': 'Entrance door',
            'value_fr': 'Aluminium + verre trempé', 'value_en': 'Aluminium + tempered glass'},
            {'label_fr': 'Résistance au vent', 'label_en': 'Wind resistance',
            'value_fr': 'Jusqu\'à 100 km/h', 'value_en': 'Up to 100 km/h'},
        ],
        'specs_int': [
            {'label_fr': 'Sol principal', 'label_en': 'Main floor',
            'value_fr': 'Revêtement SPC', 'value_en': 'SPC flooring'},
            {'label_fr': 'Isolation', 'label_en': 'Insulation',
            'value_fr': 'Panneaux isolants PIR', 'value_en': 'PIR insulation panels'},
            {'label_fr': 'Électricité', 'label_en': 'Electrical',
            'value_fr': 'Installation NF C 15-100', 'value_en': 'NF C 15-100 wiring'},
        ],
        'equipements_fr': [
            'Structure aluminium triangulée', 'Vitrage double sécurit',
            'Isolation thermique renforcée', 'Sanitaire équipé (WC, douche, lavabo)',
            'Installation électrique NF C 15-100', 'Ventilation anti-humidité',
        ],
        'equipements_en': [
            'Triangulated aluminium structure', 'Tempered double glazing',
            'Enhanced thermal insulation', 'Equipped bathroom (toilet, shower, sink)',
            'NF C 15-100 electrical wiring', 'Anti-humidity ventilation',
        ],
        'options_fr': ['Chauffage additionnel', 'Kit autonomie énergie (photovoltaïque)', 'Mezzanine (formats 38 m² et +)', 'Occultation extérieure'],
        'options_en': ['Additional heating', 'Energy autonomy kit (solar)', 'Mezzanine (38 sqm+ formats)', 'Outdoor blackout cover'],
        'usages': ['Logement', 'Bureau', 'Résidence secondaire', 'Location & Airbnb'],
    },
    {
        'slug': 'modulaire',
        'status': GAMME_STATUS_A_CONFIRMER,
        'icon': 'fa-puzzle-piece', 'name': 'Modulaire', 'indicative': False,
        'tagline_fr': 'Système extensible — formats à définir',
        'tagline_en': 'Extensible system — formats to be defined',
        'performances': [], 'formats': [], 'specs_ext': [], 'specs_int': [],
        'equipements_fr': [], 'equipements_en': [], 'options_fr': [], 'options_en': [],
        'usages': [],
    },
    {
        'slug': 'pliable',
        'status': GAMME_STATUS_A_CONFIRMER,
        'icon': 'fa-inbox', 'name': 'Pliable', 'indicative': False,
        'tagline_fr': 'Structure repliable — formats à définir',
        'tagline_en': 'Foldable structure — formats to be defined',
        'performances': [], 'formats': [], 'specs_ext': [], 'specs_int': [],
        'equipements_fr': [], 'equipements_en': [], 'options_fr': [], 'options_en': [],
        'usages': [],
    },
]

USAGES_DATA = [
    {
        'slug': 'logement',
        'icon': 'fa-home',
        'name_fr': 'Logement',
        'name_en': 'Housing',
        'bullets_fr': [
            "Installation plus rapide qu'une construction traditionnelle",
            'Autonome sur un petit terrain',
            'Alternative à un achat immobilier classique',
        ],
        'bullets_en': [
            'Faster to install than traditional construction',
            'Self-contained on a small plot',
            'An alternative to a traditional home purchase',
        ],
    },
    {
        'slug': 'bureau',
        'icon': 'fa-briefcase',
        'name_fr': 'Bureau',
        'name_en': 'Office',
        'bullets_fr': [
            'Espace de travail séparé du logement',
            'Installation indépendante sur votre terrain',
            'Calme et intimité pour se concentrer',
        ],
        'bullets_en': [
            'Work space separate from the home',
            'Standalone installation on your plot',
            'Quiet and private for focused work',
        ],
    },
    {
        'slug': 'residence-secondaire',
        'icon': 'fa-sun-o',
        'name_fr': 'Résidence secondaire',
        'name_en': 'Second home',
        'bullets_fr': [
            'Installation rapide sur un terrain existant',
            'Entretien réduit par rapport à une maison classique',
            "Utilisable selon l'équipement choisi",
        ],
        'bullets_en': [
            'Quick installation on an existing plot',
            'Less upkeep than a traditional house',
            'Usable depending on the equipment chosen',
        ],
    },
    {
        'slug': 'location-airbnb',
        'icon': 'fa-key',
        'name_fr': 'Location & Airbnb',
        'name_en': 'Rental & Airbnb',
        'bullets_fr': [
            'Structure autonome et indépendante',
            'Adaptée à la location courte durée',
            'Installation flexible selon le terrain',
        ],
        'bullets_en': [
            'Self-contained, standalone structure',
            'Suited to short-term rental',
            'Flexible installation depending on the plot',
        ],
    },
    {
        'slug': 'accessoires',
        'icon': 'fa-wrench',
        'name_fr': 'Accessoires',
        'name_en': 'Accessories',
        'bullets_fr': [
            'Personnalisez votre pod selon vos besoins',
            'Ajout possible à la commande',
            'Compatible avec toutes les gammes',
        ],
        'bullets_en': [
            'Customise your pod to your needs',
            'Can be added to your order',
            'Compatible with every range',
        ],
    },
]