{
    'name': 'Monetique Theme',
    'version': '1.0',
    'summary': 'Custom website theme for Monetique',
    'author': 'Monetique',
    'license': 'LGPL-3',
    'category': 'Website',
    'depends': [
        'website',
        'website_sale',
        'multi_vendor_marketplace',
        'monetique_specs',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/website_data.xml',
        'data/logo_data.xml',
        'views/templates/header.xml',
        'views/templates/layout.xml',
        'views/templates/footer.xml',
        'views/templates/features.xml',
        'views/partials/hero.xml',
        'views/partials/dashboard.xml',
        'views/partials/home_sections.xml',
        'views/partials/vendors.xml',
        'views/partials/trustbar.xml',
        'views/pages/home.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'monetique_theme/static/src/css/layout.css',
            'monetique_theme/static/src/css/premium.css',
            'monetique_theme/static/src/css/header.css',
            'monetique_theme/static/src/css/hero.css',
            'monetique_theme/static/src/css/trustbar.css',
            'monetique_theme/static/src/css/features.css',
            'monetique_theme/static/src/css/products.css',
            'monetique_theme/static/src/css/vendors.css',
            'monetique_theme/static/src/css/footer.css',
            'monetique_theme/static/src/css/categories.css',
            'monetique_theme/static/src/css/cta.css',
            'monetique_theme/static/src/css/dashboard.css',
            'monetique_theme/static/src/css/home_sections.css',
            'monetique_theme/static/src/css/animations.css',
            'monetique_theme/static/src/css/responsive.css',
            'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
            'monetique_theme/static/src/js/main.js',
        ],
    },
    'installable': True,
    'application': True,
}
