# -*- coding: utf-8 -*-
{
    'name': 'planet Mobil- Website Planet Mobil',
    'version': '19.0.1.0.20',
    'category': 'Website/eCommerce',
    'summary': 'Page d\'accueil e-commerce Planet Mobil',
    'author': 'Planet Mobil',
    'depends': ['website', 'web', 'portal', 'website_sale', 'website_mass_mailing', 'crm', 'website_sale_wishlist', 'im_livechat', 'delivery'],
    'data': [
        'security/ir.model.access.csv',
        'views/product_views.xml',
        'views/review_views.xml',
        'views/attribute_views.xml',
        'templates/header.xml',
        'templates/layout.xml',
        'templates/footer.xml',
        'templates/homepage.xml',
        'templates/avis_page.xml',
        'templates/contact_page.xml',
        'templates/category_page.xml',
        'templates/product_page.xml',
        'templates/product_specs.xml',
        'templates/shop.xml',
        'templates/wishlist.xml',
        'data/product_categories.xml',
        'data/product_attributes.xml',
        'data/brands.xml',
        'data/demo_products.xml',
        'data/homepage_views.xml',
        'data/product_detail_views.xml',
        'data/reviews.xml',
        'data/menus.xml',
        'data/delivery_methods.xml',
        'templates/page.xml',
        'templates/politiques_cookies.xml',
        
    ],
    'assets': {
        'web.assets_frontend': [
            'website_planet_mobil/static/src/css/style.css',
            'website_planet_mobil/static/src/js/pm_cart_badge.js',
            'website_planet_mobil/static/src/js/translate_en.js',
        ],
        'web.assets_frontend_minimal': [
            'website_planet_mobil/static/src/js/main.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'post_migrate_hook': 'post_migrate_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}