from . import auto_brand
from . import auto_motorization
from . import auto_vehicle_category
from . import auto_vehicle_color
from . import auto_vehicle_option
from . import auto_vehicle_image
from . import auto_specification
from . import auto_vehicle
from . import product_template
